FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN mkdir temp

COPY cmd ./cmd
COPY pkg ./pkg
COPY ui ./ui
COPY resources ./resources

RUN go test -v ./...

RUN CGO_ENABLED=0 GOOS=linux go build -o draw cmd/main.go

FROM alpine:latest

WORKDIR /app

RUN chmod -R a+w /app

COPY --from=builder /app/draw .

ENTRYPOINT [ "./draw" ]
