
@startuml
hide empty methods
hide empty fields


class "**Legend**" as Legend {
        LegendEntry[] entries
        StringType format
}
note top: Definition of the output for\nthe legend

 

class "**LegendEntry**" as LegendEntry {
        StringType text
        StringType format
}
note top: Definition of one legend entry

 

class "**Layout**" as Layout {
        StringType id
        StringType caption
        StringType text1
        StringType text2
        Comment comment
        StringType image
        BooleanType expand
        StringType extVertical
        Layout[] vertical
        StringType extHorizontal
        Layout[] horizontal
        StringType[] tags
        Connection[] connections
        StringType format
        BooleanType dontBlockConPaths
        StringType dataLink
        BooleanType hiddenComments
}

 

class "**LayoutArray**" as LayoutArray extends List {
}

class "**Connection**" as Connection {
        StringType dest
        StringType destId
        Comment comment
        BooleanType sourceArrow
        BooleanType destArrow
        StringType format
        StringType[] tags
}

 

class "**LayoutMixin**" as LayoutMixin {
        Layout[] horizontal
        Layout[] vertical
}
note top: container to extend the layouts\nof a given layout element\nvia mixins

 

class "**Format**" as Format {
        BooleanType widthOfParent
        IntegerType fixedWidth
        IntegerType fixedHeight
        BooleanType verticalTxt
        FontDef fontCaption
        FontDef fontText1
        FontDef fontText2
        FontDef fontComment
        FontDef fontCommentMarker
        LineDef line
        FillDef fill
        IntegerType padding
        IntegerType boxMargin
        IntegerType cornerRadius
}

 

class "**FormatVariations**" as FormatVariations {
        Map<Format> hasTag
}

 


class "**Overlay**" as Overlay {
        StringType caption
        NumberType refValue
        NumberType refRadius
        NumberType centerXOffset
        NumberType centerYOffset
        Map<NumberType> layouts
        OverlayRadiusDef radiusDefs
        OverlayFormatDef formats
}
note top: Definition of a topic related\noverlay ... for instance for\nheatmaps

 


class "**OverlayRadiusDef**" as OverlayRadiusDef {
        NumberType min
        NumberType max
}
note top: definition how to calculate radius\nchanges based on a reference\nvalue

 

class "**OverlayFormatDef**" as OverlayFormatDef {
        StringType default
        OverlayGradation[] gradations
}
note top: definition what format to use\nfor a specific reference value

 

class "**OverlayGradation**" as OverlayGradation {
        NumberType limit
        StringType format
}
note top: gradation entry for switching formats\nfor overlays

 

class "**Comment**" as Comment {
        StringType text
        StringType label
        StringType format
}
note top: Object to define comments in\nthe diagrams

 

class "**FontDef**" as FontDef {
        IntegerType size
        StringType font
        FontDefTypeEnum type
        FontDefWeightEnum weight
        NumberType lineHeight
        StringType color
        FontDefAlignedEnum aligned
        IntegerType spaceTop
        IntegerType spaceBottom
        IntegerType maxLenBeforeBreak
        FontDefAnchorEnum anchor
}
note top: Defines the font a text

 

enum "FontDefTypeEnum" as FontDefTypeEnum {
    NORMAL
    ITALIC
}

enum "FontDefWeightEnum" as FontDefWeightEnum {
    NORMAL
    BOLD
}

enum "FontDefAlignedEnum" as FontDefAlignedEnum {
    LEFT
    CENTER
    RIGHT
}

enum "FontDefAnchorEnum" as FontDefAnchorEnum {
    MIDDLE
    LEFT
    RIGHT
}

class "**LineDef**" as LineDef {
        NumberType width
        LineDefStyleEnum style
        StringType color
        NumberType opacity
}
note top: Defines how the border of\nthe box looks like

 

enum "LineDefStyleEnum" as LineDefStyleEnum {
    SOLID
    DOTTED
    DASHED
}

class "**FillDef**" as FillDef {
        StringType color
        NumberType opacity
}
note top: Defines the fill of the\nbox

 

class "**ImageDef**" as ImageDef {
        StringType description
        IntegerType width
        IntegerType height
        StringType base64
        IntegerType marginTopBottom
        IntegerType marginLeftRight
        StringType base64Src
}
note top: parameters of an image to\nbe displayed in the SVG

 


    
Legend "0" *-- "n" LegendEntry


    


    




Layout  *--  Comment




Layout "0" *-- "n" Layout




Layout "0" *-- "n" Connection





    
    


Connection  *--  Comment





    
LayoutMixin "0" *-- "n" Layout


    




Format  *--  FontDef

Format  *--  FontDef

Format  *--  FontDef

Format  *--  FontDef

Format  *--  FontDef

Format  *--  LineDef

Format  *--  FillDef




    
FormatVariations  *--  Format

    
    






Overlay  *--  OverlayRadiusDef

Overlay  *--  OverlayFormatDef

    
    


    

OverlayFormatDef "0" *-- "n" OverlayGradation

    


    



    











    
    
    
    
    




    
    


    








footer \ngenerated with yacg (https://github.com/OkieOth/yacg),\n(template: plantUml.mako v1.1.0)\npowered by plantuml (https://plantuml.com/)
@enduml