
@startuml
hide empty methods
hide empty fields


class "**Gantt**" as Gantt {
        StringType title
        Group[] groups
        Event[] events
        Map<GanttFormat> formats
}
note top: Model to describe the input\nof gantt diagrams

 

class "**Group**" as Group {
        StringType name
        DateTimeType start
        DateTimeType end
        Entry[] entries
        StringType format
}

 

class "**Event**" as Event {
        DateTimeType date
        StringType text
        StringType description
        EntryRef[] entryRefs
}
note top: an event that is displayed\nin the gantt chart and\nhas references to specific group\nentries

 


class "**GanttFormat**" as GanttFormat {
        FontDef font
        FontDef groupFont
        FontDef entryFont
        FontDef eventFont
        FillDef entryFill
}

 

class "**Entry**" as Entry {
        StringType name
        DateTimeType start
        RelativeStart startsAfter
        DateTimeType end
        IntegerType duration
        StringType description
        EntryRef[] references
        StringType format
}

 

class "**RelativeStart**" as RelativeStart {
        StringType groupRef
        StringType entryRef
}

 

class "**EntryRef**" as EntryRef {
        StringType groupRef
        StringType entryRef
}

 

class "**FontDef**" as FontDef {
        IntegerType size
        StringType font
        FontDefTypeEnum type
        FontDefWeightEnum weight
        NumberType lineHeight
        StringType color
        FontDefAlignedEnum aligned
        IntegerType spaceTop
        IntegerType spaceBottom
        IntegerType maxLenBeforeBreak
        FontDefAnchorEnum anchor
}
note top: Defines the font a text

 

enum "FontDefTypeEnum" as FontDefTypeEnum {
    NORMAL
    ITALIC
}

enum "FontDefWeightEnum" as FontDefWeightEnum {
    NORMAL
    BOLD
}

enum "FontDefAlignedEnum" as FontDefAlignedEnum {
    LEFT
    CENTER
    RIGHT
}

enum "FontDefAnchorEnum" as FontDefAnchorEnum {
    MIDDLE
    LEFT
    RIGHT
}

class "**LineDef**" as LineDef {
        NumberType width
        LineDefStyleEnum style
        StringType color
        NumberType opacity
}
note top: Defines how the border of\nthe box looks like

 

enum "LineDefStyleEnum" as LineDefStyleEnum {
    SOLID
    DOTTED
    DASHED
}

class "**FillDef**" as FillDef {
        StringType color
        NumberType opacity
}
note top: Defines the fill of the\nbox

 

class "**ImageDef**" as ImageDef {
        StringType description
        IntegerType width
        IntegerType height
        StringType base64
        IntegerType marginTopBottom
        IntegerType marginLeftRight
        StringType base64Src
}
note top: parameters of an image to\nbe displayed in the SVG

 


    

Gantt "0" *-- "n" Group

Gantt "0" *-- "n" Event

Gantt  *--  GanttFormat

    



Group "0" *-- "n" Entry


    



Event "0" *-- "n" EntryRef

    
    
GanttFormat  *--  FontDef

GanttFormat  *--  FontDef

GanttFormat  *--  FontDef

GanttFormat  *--  FontDef

GanttFormat  *--  FillDef

    


Entry  *--  RelativeStart




Entry "0" *-- "n" EntryRef


    


    


    











    
    
    
    
    




    
    


    








footer \ngenerated with yacg (https://github.com/OkieOth/yacg),\n(template: plantUml.mako v1.1.0)\npowered by plantuml (https://plantuml.com/)
@enduml