
@startuml
hide empty methods
hide empty fields


class "**FontDef**" as FontDef {
        IntegerType size
        StringType font
        FontDefTypeEnum type
        FontDefWeightEnum weight
        NumberType lineHeight
        StringType color
        FontDefAlignedEnum aligned
        IntegerType spaceTop
        IntegerType spaceBottom
        IntegerType maxLenBeforeBreak
        FontDefAnchorEnum anchor
}
note top: Defines the font a text

 

enum "FontDefTypeEnum" as FontDefTypeEnum {
    NORMAL
    ITALIC
}

enum "FontDefWeightEnum" as FontDefWeightEnum {
    NORMAL
    BOLD
}

enum "FontDefAlignedEnum" as FontDefAlignedEnum {
    LEFT
    CENTER
    RIGHT
}

enum "FontDefAnchorEnum" as FontDefAnchorEnum {
    MIDDLE
    LEFT
    RIGHT
}

class "**LineDef**" as LineDef {
        NumberType width
        LineDefStyleEnum style
        StringType color
        NumberType opacity
}
note top: Defines how the border of\nthe box looks like

 

enum "LineDefStyleEnum" as LineDefStyleEnum {
    SOLID
    DOTTED
    DASHED
}

class "**FillDef**" as FillDef {
        StringType color
        NumberType opacity
}
note top: Defines the fill of the\nbox

 

class "**ImageDef**" as ImageDef {
        StringType description
        IntegerType width
        IntegerType height
        StringType base64
        IntegerType marginTopBottom
        IntegerType marginLeftRight
        StringType base64Src
}
note top: parameters of an image to\nbe displayed in the SVG

 


    











    
    
    
    
    




    
    


    








footer \ngenerated with yacg (https://github.com/OkieOth/yacg),\n(template: plantUml.mako v1.1.0)\npowered by plantuml (https://plantuml.com/)
@enduml